---
- name: create a VPC
  ec2_vpc_net:
    name: "{{vpc_name}}"
    cidr_block: "{{cidr_block}}"
    region: "{{aws_region}}"
    tags: "{{vpc_tags}}"
    dns_hostnames: "{{dns_hostname}}"
    dns_support: "{{dns_support}}"
    dhcp_opts_id: "{{dhcp_info.dhcp_options[0].dhcp_options_id}}"
    multi_ok: no
    purge_cidrs: yes
    state: present
    tenancy: "{{tenancy}}"
  register: vpc
- debug: var=vpc